settings:
  kubeContext: kind-${K8S_DEV_CLUSTER_NAME}
helmRepos:
  ingress-nginx: https://kubernetes.github.io/ingress-nginx
  docker-registry: https://helm.twun.io
namespaces:
  ingress-nginx:
  docker-registry:
apps:
  ingress-nginx:
    name: ingress-nginx
    description: NGINX ingress
    namespace: ingress-nginx
    chart: "ingress-nginx/ingress-nginx"
    version: "4.0.13"
    enabled: true
    priority: -1000
    set:
      controller.admissionWebhooks.enabled: false
      controller.config.proxy-body-size: "0"
  docker-registry:
    name: docker-registry
    description: Cluster's local docker registry
    namespace: docker-registry
    chart: "docker-registry/docker-registry"
    version: "1.16.0"
    enabled: true
    priority: -999
    set:
      service.type: NodePort
      service.nodePort: 30000
      ingress.enabled: true
      ingress.hosts[0]: docker-registry.${K8S_DEV_CLUSTER_NAME}.localdev.me
      ingress.annotations.kubernetes\.io/ingress\.class: nginx
