settings:
  kubeContext: kind-${K8S_DEV_CLUSTER_NAME}
helmRepos:
  nginx-ingress: https://kubernetes.github.io/ingress-nginx
  docker-registry: https://helm.twun.io
  prometheus-community: https://prometheus-community.github.io/helm-charts
  keycloak: https://charts.bitnami.com/bitnami
namespaces:
  nginx-ingress:
  docker-registry:
  kube-prometheus:
  keycloak:
apps:
  nginx-ingress:
    name: nginx-ingress
    description: NGINX ingress
    namespace: nginx-ingress
    chart: "nginx-ingress/ingress-nginx"
    version: "4.0.16"
    enabled: true
    priority: -1000
    set:
      nameOverride: nginx-ingress
      controller.admissionWebhooks.enabled: false
      controller.config.proxy-body-size: "0"
  docker-registry:
    name: docker-registry
    description: Cluster's local docker registry
    namespace: docker-registry
    chart: "docker-registry/docker-registry"
    version: "2.0.0"
    enabled: true
    priority: -999
    set:
      service.type: NodePort
      service.nodePort: 30000
      ingress.enabled: true
      ingress.hosts[0]: docker-registry.${K8S_DEV_CLUSTER_NAME}.localdev.me
      ingress.className: nginx
  kube-prometheus:
    name: kube-prometheus
    description: kube-prometheus stack
    namespace: kube-prometheus
    chart: "prometheus-community/kube-prometheus-stack"
    version: "36.6.2"
    enabled: true
    priority: -998
    set:
      grafana.ingress.enabled: true
      grafana.ingress.ingressClassName: nginx
      grafana.ingress.hosts[0]: grafana.${K8S_DEV_CLUSTER_NAME}.localdev.me
      grafana.adminPassword: password
  keycloak:
    name: keycloak
    description: Keycloak
    namespace: keycloak
    chart: "keycloak/keycloak"
    version: "6.1.1"
    enabled: true
    priority: -997
    set:
      ingress.enabled: true
      ingress.hostname: keycloak.${K8S_DEV_CLUSTER_NAME}.localdev.me
      ingress.ingressClassName: nginx
      auth.adminUser: admin
      auth.adminPassword: admin
