apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: ${K8S_DEV_CLUSTER_NAME} # subsitituted with envsubst
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker-registry.cluster.local"]
    endpoint = ["http://localhost:30000"]
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: KubeProxyConfiguration
      metricsBindAddress: 0.0.0.0
    - |
      kind: ClusterConfiguration
      etcd:
        local:
          extraArgs:
            listen-client-urls: "https://0.0.0.0:2379,http://0.0.0.0:2379"
      controllerManager:
        extraArgs:
          bind-address: 0.0.0.0
      scheduler:
        extraArgs:
          bind-address: 0.0.0.0
  # - role: worker
  # - role: worker
